In [1]:
import torch
import numpy as np

# Creating a tensor from a list
tensor_from_list = torch.tensor([1, 2, 3, 4])

# Creating a tensor from a NumPy array
numpy_array = np.array([1, 2, 3, 4])
tensor_from_numpy = torch.from_numpy(numpy_array)

print(tensor_from_list)
print(tensor_from_numpy)


tensor([1, 2, 3, 4])
tensor([1, 2, 3, 4])


In [2]:
# Mathematical operation
result = tensor_from_list + tensor_from_numpy

# Reshaping a tensor
reshaped = tensor_from_list.view(2, 2)

print(result)
print(reshaped)


tensor([2, 4, 6, 8])
tensor([[1, 2],
        [3, 4]])


In [3]:
# Enabling gradient computation
x = torch.tensor([1.0, 2.0, 3.0, 4.0], requires_grad=True)
y = 2 * x + 3

# print(y.grad_fn)


In [4]:
# Compute the gradient
y.backward(torch.tensor([1.0, 1.0, 1.0, 1.0]))
print(x.grad)


tensor([2., 2., 2., 2.])


In [8]:
# Generate dummy data
x = torch.randn(100, 1) * 10 # 100 rows, 1 column
print(x.shape)
y = x + 3*torch.randn(100, 1)
print(y.shape)

# Initialize weights and bias with requires_grad=True
weights = torch.randn(1, requires_grad=True)
bias = torch.randn(1, requires_grad=True)

# Simple training loop
learning_rate = 0.001
for i in range(1000):
    prediction = x * weights + bias
    loss = ((prediction - y)**2).mean()  # Mean Squared Error

    # Compute gradients
    loss.backward()

    # Update weights and biases
    with torch.no_grad():
        weights -= learning_rate * weights.grad
        bias -= learning_rate * bias.grad

    # Zero the gradients after updating
    weights.grad.zero_()
    bias.grad.zero_()

print(f"Trained weights: {weights.item()}, bias: {bias.item()}")


tensor([[ -9.6537],
        [ -4.1069],
        [ -5.1019],
        [ 12.4437],
        [-16.6894],
        [ 12.6265],
        [  2.5928],
        [  1.6393],
        [-14.8592],
        [ 18.7561],
        [ -1.0067],
        [ -6.5456],
        [ -0.1215],
        [  2.2519],
        [ 11.9072],
        [ -9.8172],
        [ -9.9966],
        [  2.0139],
        [ 10.8131],
        [ -9.6774],
        [ -3.2945],
        [ -3.2199],
        [-14.6552],
        [ -6.3690],
        [  2.4106],
        [  6.5310],
        [  9.3975],
        [ -5.7364],
        [ -3.5922],
        [ -5.8718],
        [-16.9570],
        [ -3.3146],
        [  1.5833],
        [  5.4712],
        [ -5.6247],
        [  2.8722],
        [  1.9623],
        [  4.4600],
        [ 14.2285],
        [  1.8862],
        [  2.8569],
        [ 10.3572],
        [  1.9451],
        [  7.6473],
        [ -0.5308],
        [-11.6181],
        [  7.3707],
        [  4.5728],
        [  5.6276],
        [ -3.7460],
